#!/usr/bin/env bash

set -euo pipefail

if [[ ! -z ${VERBOSE+x} ]]; then
  set -x
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd infrastructure >/dev/null
  # Setup terraform remote state
  terraform remote config -backend s3         \
    -backend-config "bucket=sauron-terraform" \
    -backend-config "key=terraform.tfstate"

  aws s3 cp s3://sauron-terraform/terraform.tfvars .
popd >/dev/null

"$DIR/../deploy"
