#!/usr/bin/env bash

set -euo pipefail

if [[ ! -z ${VERBOSE+x} ]]; then
  set -x
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Move the project into the right location
rm -rf "$PROJECT"
mkdir -p "$(dirname "$PROJECT")"
mv "$HOME/sauron" "$PROJECT"
ln -s "$PROJECT" "$HOME/sauron"

# Install dependencies
"$DIR/install-go"
"$DIR/install-terraform"
"$DIR/install-apex"
