#!/usr/bin/env bash

set -euo pipefail

if [[ ! -z ${VERBOSE+x} ]]; then
  set -x
fi

if [[ ! -z ${CI+x} ]]; then
  COMMIT_MSG="$(git log -1 --pretty=%B)"
  if [[ "$COMMIT_MSG" != *\[release\]* ]]; then
    exit 0
  fi
fi

pushd cmd/sauron > /dev/null
  gox -arch "!386 !arm" -ldflags "-X main.Version=$CIRCLE_BUILD_NUM" -output "dist/sauron_{{.OS}}_{{.Arch}}"
  ghr -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME "v0.$CIRCLE_BUILD_NUM" dist/
popd > /dev/null
